name: Deploy Backend API

on:
  push:
    branches: [master]

name: Deploy to AWS
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Lambda Artifact
        run: make build
      - name: Deploy to AWS
        uses: serverless/github-action@master
        with:
          args: deploy --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}